name: Aurora Data Sync (with Dividend Planner)

on:
  schedule:
    # Runs hourly during UK market hours (08:00–16:00 UTC, Mon–Fri)
    - cron: "0 8-16 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # --------------------------------------
      # 1️⃣ Checkout repository (main branch)
      # --------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      # --------------------------------------
      # 2️⃣ Fetch Holdings + Dividends feeds from Google Sheets
      # --------------------------------------
      - name: Fetch latest feeds
        run: |
          echo "📥 Fetching data from Google Sheets..."
          curl -sL "https://opensheet.elk.sh/10MdgQKc4tParno7pNkz40eBGz308wxHu1u3gvJe_WsE/Holdings" -o holdings.json
          curl -sL "https://opensheet.elk.sh/10MdgQKc4tParno7pNkz40eBGz308wxHu1u3gvJe_WsE/Dividends" -o dividends.json

      # --------------------------------------
      # 3️⃣ Validate feeds
      # --------------------------------------
      - name: Validate JSON feeds
        run: |
          sudo apt-get update -qq && sudo apt-get install -y jq python3-dateutil
          jq empty holdings.json  || { echo "❌ Holdings feed invalid"; exit 1; }
          jq empty dividends.json || { echo "❌ Dividends feed invalid"; exit 1; }
          echo "✅ JSON feeds validated successfully."

      # --------------------------------------
      # 4️⃣ Merge feeds into AuroraSync.json
      # --------------------------------------
      - name: Merge feeds into AuroraSync.json
        run: |
          echo "🔄 Merging feeds into AuroraSync.json..."
          [ -f AuroraSync.json ] || echo '{}' > AuroraSync.json
          jq --slurpfile h holdings.json --slurpfile d dividends.json \
             '.isa_feed = $h[0] | .dividends_feed = $d[0]' AuroraSync.json > tmp && mv tmp AuroraSync.json
          echo "✅ Feeds merged."

      # --------------------------------------
      # 5️⃣ Auto-generate Dividend Planner (12-month forecast)
      # --------------------------------------
      - name: Build Dividend Planner
        run: |
          echo "🧮 Generating 12-month Dividend Planner..."
          python3 <<'PYCODE'
          import json, datetime, collections
          from dateutil import parser

          with open("AuroraSync.json") as f:
              data = json.load(f)

          feed = data.get("dividends_feed", [])
          months = collections.OrderedDict()
          today = datetime.date.today()
          one_year = today + datetime.timedelta(days=365)

          for d in feed:
              try:
                  pay = parser.parse(d.get("pay_date","")).date()
              except Exception:
                  continue
              if today <= pay <= one_year:
                  key = pay.strftime("%b %Y")
                  months[key] = months.get(key, 0) + float(d.get("total_dividend", 0))

          ann_total = sum(months.values())
          monthly = [{"month": k, "total_estimated_income": round(v,2)} for k,v in months.items()]
          qtrs = {"Q1":0,"Q2":0,"Q3":0,"Q4":0}
          for i,(m,v) in enumerate(months.items()):
              q = (i//3)+1
              qtrs[f"Q{q}"] += round(v,2)

          planner = {
              "auto_generated": True,
              "source": "dividends_feed",
              "annual_total": round(ann_total,2),
              "received_ytd": 0,
              "forecast_total": round(ann_total,2),
              "quarterly_breakdown": qtrs,
              "monthly_breakdown": monthly,
              "cashflow_projection": {
                  "forecast_window": f"{today:%b %Y}–{one_year:%b %Y}",
                  "monthly_forecast": [
                      {"month": k, "expected_dividends": round(v,2),
                       "expected_interest": 0, "total": round(v,2)} for k,v in months.items()
                  ],
                  "annual_total_projection": round(ann_total,2),
                  "rolling_average_monthly_income": round(ann_total/12,2),
                  "target_yearly_income": 6000,
                  "percent_to_goal": round((ann_total/6000)*100,2)
              }
          }

          data["dividend_planner"] = planner

          with open("AuroraSync.json","w") as f:
              json.dump(data,f,indent=2)
          PYCODE
          echo "✅ Dividend Planner generated successfully."

      # --------------------------------------
      # 6️⃣ Commit & Push updates
      # --------------------------------------
      - name: Commit and push changes
        run: |
          git config user.name  "Aurora Sync Bot"
          git config user.email "aurora-sync@users.noreply.github.com"
          git add AuroraSync.json
          git diff --cached --quiet && echo "No changes to commit." && exit 0
          git commit -m "🔄 Auto-update AuroraSync.json (Feeds + Dividend Planner)"
          git push origin main
          echo "✅ AuroraSync.json updated and pushed."